### ISSUE TITLE
`stop` does not appear to work

### ISSUE THREAD

**Issue by vadim-ex** [CargoSense/ex_statsd#15]
```
     ** (exit) exited in: GenServer.call(ExStatsD, :stop, 5000)
         ** (EXIT) bad call: :stop   
     stacktrace:
       (elixir) lib/gen_server.ex:544: GenServer.call/3
    ...
```

**Comment by benwilson512** [comment]
I'll look into it. In general you shouldn't be manually stopping or starting ex_statsd, but rather including it in your mix.exs applications list.

**Comment by vadim-moz** [comment]
I do not start manually. However, manual stop is the only way to ensure (in current version) that all the metrics are reported to the server before application completes orderly.
