### ISSUE TITLE
Add a `flush` call

### ISSUE THREAD

**Issue by vadim-moz** [CargoSense/ex_statsd#16]
The idea is to force message queue flush (for example, before closing program). I can submit PR if it would help.

(The idea is similar to Logger.flush)

**Comment by benwilson512** [comment]
It wasn't my impression that ex_statsd buffered anything. What is it that ex_statsd has that needs flushed?

**Comment by vadim-moz** [comment]
It uses GenServer cast, which queues up messages in the ExStatsD message queue. The queue might grow rather big (to the degree it would crush BEAM). This is why Elixir Logger employs mixed strategy (https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L15)

The more important consideration for us is application termination (for command-line utility). Because of asynchronous operation, the metrics are not reported to the server (it is race condition).

**Comment by benwilson512** [comment]
ah I see. So you're running something, it's casting to ExStatsd, and then exiting before statsd has a chance to process its inbox is that it?

**Comment by vadim-moz** [comment]
Correct! So `flush` is essentially no-op, but using `GenServer.call` for communication.

**Comment by benwilson512** [comment]
Yup gotcha. Ok we can do this. Feel free to do a PR given that it really is a no-op (should just return :ok). If not I'll get to it in the next few days.

**Comment by vadim-moz** [comment]
OK -- I am planning for later today.

**Comment by benwilson512** [comment]
Fixed by #17

**Comment by vadim-moz** [comment]
Thank you! Would you mind to bump version?

**Comment by benwilson512** [comment]
Yeah my thought is that I would fix the stop thing here this afternoon and then release both under a new version.

**Comment by vadim-moz** [comment]
Thank you!

**Comment by vadim-moz** [comment]
Hi Ben,

Do you want me to try to fix `GenServer`? I am not as sure with solution as
with `.flush`, but I can try.

Thank you,

Vadim

*/Vadim*
