### ISSUE TITLE
Messages to ExStatsd backup with high throughput web app

### ISSUE THREAD

**Issue by forest** [CargoSense/ex_statsd#18]
I recently experienced an issue where the ExStatsd processes message mailbox got backed up with 200k+ messages. My web api is processing 300 req/s and has 5 stats. After a couple of minutes the ExStatsd process has over 200k messages to process.

I think adding a configurable worker pool would greatly help.

In the short term I switch to using https://github.com/lexmag/statix which was able to handle the high throughput.

**Comment by AndrewDryga** [comment]
We have same issue 👎 

<img width="1440" alt="2017-02-02 20 54 02" src="https://cloud.githubusercontent.com/assets/1877644/22563652/35087cda-e98a-11e6-952b-799df9387db6.png">

**Comment by joshuawscott** [comment]
@AndrewDryga We've gotten past this by turning on sampling for things using ex_statsd in production.

**Comment by lexmag** [comment]
@AndrewDryga @joshuawscott if you need to handle very high throughput without using sampling (there are sometimes requirements for that) I recommend checking https://github.com/lexmag/statix.
It can tolerate 50k increments per second with no degradation in the system.

**Comment by benwilson512** [comment]
I've been meaning to evaluate some of the other statsd clients that have shown up over time. It may well make sense to retire this library in favor of one of the others. Cargosense has quite a few libraries out at this point and not all of them are getting the attention they deserve.

**Comment by AndrewDryga** [comment]
@lexmag thanks, we already investigating your lib. This one looks abandoned (no updated to hex package).

**Comment by lexmag** [comment]
@benwilson512 perhaps it would help people in discovering alternatives.
Big 💛 for you work on ExAws.

**Comment by mmmries** [comment]
I've run into this same problem on my system, usually it happens right after a restart when the system is under load. If I kill the process it can then keep up with the throughput just fine.

![screen shot 2017-06-02 at 10 21 54 am](https://cloud.githubusercontent.com/assets/80008/26735278/724ba750-477e-11e7-9ece-db92933d25ec.png)

It appears that `:inet.udp_close/1` is what got stuck, maybe there's a way to detect why the UDP close is getting jammed?
