### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by predrag-rakic** [CargoSense/ex_statsd#26]
```
git clone git@github.com:CargoSense/ex_statsd.git
cd ex_statsd/
mix deps.get
mix test
** (CompileError) test/lib/ex_statsd_test.exs:4: undefined function describe/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

What am I doing wrong?

**Comment by benwilson512** [comment]
What version of elixir are you on?

**Comment by predrag-rakic** [comment]
Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.6

**Comment by benwilson512** [comment]
Right, `describe` was added in 1.3: http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Case.html#describe/2

While ex_statsd will happily run in earlier elixir versions, the test suite requires 1.3

**Comment by predrag-rakic** [comment]
tnx
