### ISSUE TITLE
Support run-time environment config

### ISSUE THREAD

**Issue by AndrewDryga** [CargoSense/ex_statsd#27]
It would be awesome to use run-time environment to configure ex_statsd. You can find helpful lib here: github.com/Nebo15/confex

Example:

```
config :ex_statsd,
       host: {:system, "STATSD_HOST", "localhost"},
       port: {:system, :integer, "STATSD_PORT", 8125},
       namespace: {:system, "STATSD_NAMESPACE", "os.gateway"}
```

**Comment by benwilson512** [comment]
PR would be welcome.

There is no need to add a dependency, it's a pretty easy thing to handle.
