### ISSUE TITLE
Release new version to hex.pm

### ISSUE THREAD

**Issue by AndrewDryga** [CargoSense/ex_statsd#28]
Hello,

We always have nasty warnings that was fixed in this [merge](https://github.com/CargoSense/ex_statsd/commit/8627cae80e5cc5221740b2d854d19c01dd904cd0). Can you, please, publish a new package so our eyes will stop bleeding? :dancing_men:

**Comment by asummers** [comment]
I second this for the exact same merge. We would greatly appreciate it as well =)

**Comment by benrom** [comment]
@bruce is it possible to create a new hex release? Cheers!

**Comment by slashmili** [comment]
Please @bruce 🙏

**Comment by lpil** [comment]
It'd be great to get this stuff released :)

**Comment by hauleth** [comment]
Ping? @bruce if you aren't interested in keeping this up then you could look for someone else interested in maintaining this repo.
