### ISSUE TITLE
Sampling implementation

### ISSUE THREAD

**Issue by alexdias** [CargoSense/ex_statsd#38]
Hello,

We seem to be encountering issues with sampling when the sample rate is set to a relatively low value. As far as I understand from the implementation [here](https://github.com/CargoSense/ex_statsd/blob/master/lib/ex_statsd.ex#L270), the code takes a random number from 0 to 1, and compares it to the sample rate.

Is this correct? We have our sample rate set to 0.1 (10%), and we were expecting one in every ten values to be sent, but this does not seem to be the case (as the random number generation is independent from call to call).

Could the implementation be changed to something deterministic, like keeping a counter?

**Comment by joshuawscott** [comment]
What version are you on? There was a change made in #31 that switched to the newer `:rand` module. The older module had issues with seeding that would show up if you had short-lived processes.

I'm on the latest commit, and have no issues with a sample rate of 0.02 now.
